exports_files(
    glob(["*.tql"])
)

filegroup(
    name = "data-csv",
    srcs = glob(["data/*.csv"]),
    visibility = ["//visibility:public"]
)

filegroup(
    name = "data-json",
    srcs = glob(["data/*.json"]),
    visibility = ["//visibility:public"]
)

filegroup(
    name = "data-xml",
    srcs = glob(["data/*.xml"]),
    visibility = ["//visibility:public"]
)
