{
  cardholders {
    firstName
    lastName
    birthDate
    gender
    job
    address {
      city
      state
      street
      zip
    }
    coords {
      latitude
      longitude
    }
    card {
      number
      bank {
        name
        coords {
          latitude
          longitude
        }
      }
    }
  }
}